from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput


class AttackerInput(GridLayout):
    ap = TextInput(text="ap", size_hint=(0.1, "20sp"))
    aap = TextInput(text="aap", size_hint=("20sp", "20sp"))
    acc = TextInput(size_hint=("20sp", "20sp"))
    acc_rate = TextInput(size_hint=("20sp", "20sp"))
    crit_rate = TextInput(size_hint=("20sp", "20sp"))
    monster_ap = TextInput(size_hint=("20sp", "20sp"))
    kama_damage = TextInput(size_hint=("20sp", "20sp"))
    demi_damage = TextInput(size_hint=("20sp", "20sp"))
    human_damage = TextInput(size_hint=("20sp", "20sp"))
    other_damage = TextInput(size_hint=("20sp", "20sp"))
    crit_damage = TextInput(size_hint=("20sp", "20sp"))
    class_id = TextInput(text="class", size_hint=("20sp", "20sp"))
    back_damage = TextInput(size_hint=("20sp", "20sp"))
    down_damage = TextInput(size_hint=("20sp", "20sp"))
    air_damage = TextInput(size_hint=("20sp", "20sp"))
    ap_combat_buffs = TextInput(size_hint=("20sp", "20sp"))
    crit_combat_buffs = TextInput(size_hint=("20sp", "20sp"))
    ap_debuffs = TextInput(size_hint=("20sp", "20sp"))
    acc_combat_buffs = TextInput(size_hint=("20sp", "20sp"))
    acc_debuffs = TextInput(size_hint=("20sp", "20sp"))
    human_damage_debuffs = TextInput(size_hint=("20sp", "20sp"))

    def __init__(self, **kwargs):
        super(AttackerInput, self).__init__(**kwargs)
        # --
        self.add_widget(self.class_id, index=1)
        self.add_widget(self.ap, index=2)
        self.add_widget(self.aap, index=3)
        self.add_widget(self.acc, index=4)
        self.add_widget(self.acc_rate, index=5)
        self.add_widget(self.crit_rate, index=6)
        self.add_widget(self.monster_ap, index=7)
        self.add_widget(self.kama_damage, index=8)
        self.add_widget(self.demi_damage, index=9)
        self.add_widget(self.human_damage, index=10)
        self.add_widget(self.other_damage, index=11)
        self.add_widget(self.crit_damage, index=12)
        self.add_widget(self.back_damage, index=13)
        self.add_widget(self.down_damage, index=14)
        self.add_widget(self.air_damage, index=15)
        self.add_widget(self.ap_combat_buffs, index=16)
        self.add_widget(self.crit_combat_buffs, index=17)
        self.add_widget(self.ap_debuffs, index=18)
        self.add_widget(self.acc_combat_buffs, index=19)
        self.add_widget(self.acc_debuffs, index=20)
        self.add_widget(self.human_damage_debuffs, index=21)
